"""Начальная схема БД

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 20:20:27.664348
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('single_per_user', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_to >= date_from', name='ck_holiday_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date_from'), 'holidays', ['date_from'], unique=False)
    op.create_table('income_kinds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_from', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_to', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('income_from >= 0', name='ck_tax_from_nonneg'),
    sa.CheckConstraint('income_to IS NULL OR income_to > income_from', name='ck_tax_range'),
    sa.CheckConstraint('rate >= 0 AND rate <= 100', name='ck_tax_rate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('advance_day', sa.SmallInteger(), nullable=True),
    sa.Column('salary_day', sa.SmallInteger(), nullable=True),
    sa.Column('advance_calc_day', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('advance_calc_day IS NULL OR advance_calc_day BETWEEN 1 AND 31', name='ck_users_advance_calc_day'),
    sa.CheckConstraint('advance_day IS NULL OR advance_day BETWEEN 1 AND 31', name='ck_users_advance_day'),
    sa.CheckConstraint('salary IS NULL OR salary >= 0', name='ck_users_salary_nonneg'),
    sa.CheckConstraint('salary_day IS NULL OR salary_day BETWEEN 1 AND 31', name='ck_users_salary_day'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('replenish_period', sa.Enum('none', 'weekly', 'monthly', 'quarterly', 'yearly', name='replenish_period'), nullable=False),
    sa.Column('replenish_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('months_to_goal', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('months_to_goal IS NULL OR months_to_goal > 0', name='ck_accounts_months_pos'),
    sa.CheckConstraint('replenish_amount IS NULL OR replenish_amount > 0', name='ck_accounts_replenish_pos'),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_index('uq_accounts_owner_name_open', 'accounts', ['owner_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('NOT is_closed'))
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('planning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('amount_planned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('operation_type_id', sa.Integer(), nullable=False),
    sa.Column('income_kind_id', sa.Integer(), nullable=True),
    sa.Column('funding_account_id', sa.UUID(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_net IS NULL OR amount_net >= 0', name='ck_planning_net_nonneg'),
    sa.CheckConstraint('amount_planned > 0', name='ck_planning_amount_pos'),
    sa.CheckConstraint('tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 100)', name='ck_planning_tax_rate'),
    sa.ForeignKeyConstraint(['funding_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['income_kind_id'], ['income_kinds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planning_owner_date', 'planning', ['owner_id', 'planned_date'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('operation_type_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('target_account_id', sa.UUID(), nullable=True),
    sa.Column('op_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_operations_amount_pos'),
    sa.CheckConstraint('target_account_id IS NULL OR target_account_id <> account_id', name='ck_operations_transfer_distinct'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['planning.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operations_account', 'operations', ['account_id'], unique=False)
    op.create_index('ix_operations_owner_date', 'operations', ['owner_id', 'op_date'], unique=False)
    op.create_index('ix_operations_plan', 'operations', ['plan_id'], unique=False)
    op.create_index('ix_operations_target_account', 'operations', ['target_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operations_target_account', table_name='operations')
    op.drop_index('ix_operations_plan', table_name='operations')
    op.drop_index('ix_operations_owner_date', table_name='operations')
    op.drop_index('ix_operations_account', table_name='operations')
    op.drop_table('operations')
    op.drop_index('ix_planning_owner_date', table_name='planning')
    op.drop_table('planning')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('uq_accounts_owner_name_open', table_name='accounts', postgresql_where=sa.text('NOT is_closed'))
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('tax_brackets')
    op.drop_table('operation_types')
    op.drop_table('income_kinds')
    op.drop_index(op.f('ix_holidays_date_from'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_table('app_settings')
    op.drop_table('account_types')
    sa.Enum(name='replenish_period').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
